CREATE TABLE city (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	province INT NOT NULL,
	population INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 	PRIMARY KEY city_pk (id),
    FOREIGN KEY city_province_fk (province) REFERENCES province(id)
)