INSERT INTO province (name) VALUES ("Albacete");
INSERT INTO province (name) VALUES ("Alicante/Alacant");
INSERT INTO province (name) VALUES ("Almería");
INSERT INTO province (name) VALUES ("Araba/Álava");
INSERT INTO province (name) VALUES ("Asturias");
INSERT INTO province (name) VALUES ("Ávila");
INSERT INTO province (name) VALUES ("Badajoz");
INSERT INTO province (name) VALUES ("Balears, Illes");
INSERT INTO province (name) VALUES ("Barcelona");
INSERT INTO province (name) VALUES ("Bizkaia");
INSERT INTO province (name) VALUES ("Burgos");
INSERT INTO province (name) VALUES ("Cáceres");
INSERT INTO province (name) VALUES ("Cádiz");
INSERT INTO province (name) VALUES ("Cantabria");
INSERT INTO province (name) VALUES ("Castellón/Castelló");
INSERT INTO province (name) VALUES ("Ceuta");
INSERT INTO province (name) VALUES ("Ciudad Real");
INSERT INTO province (name) VALUES ("Córdoba");
INSERT INTO province (name) VALUES ("Coruña, A");
INSERT INTO province (name) VALUES ("Cuenca");
INSERT INTO province (name) VALUES ("Gipuzkoa");
INSERT INTO province (name) VALUES ("Girona");
INSERT INTO province (name) VALUES ("Granada");
INSERT INTO province (name) VALUES ("Guadalajara");
INSERT INTO province (name) VALUES ("Huelva");
INSERT INTO province (name) VALUES ("Huesca");
INSERT INTO province (name) VALUES ("Jaén");
INSERT INTO province (name) VALUES ("León");
INSERT INTO province (name) VALUES ("Lleida");
INSERT INTO province (name) VALUES ("Lugo");
INSERT INTO province (name) VALUES ("Madrid");
INSERT INTO province (name) VALUES ("Málaga");
INSERT INTO province (name) VALUES ("Melilla");
INSERT INTO province (name) VALUES ("Murcia");
INSERT INTO province (name) VALUES ("Navarra");
INSERT INTO province (name) VALUES ("Ourense");
INSERT INTO province (name) VALUES ("Palencia");
INSERT INTO province (name) VALUES ("Palmas, Las");
INSERT INTO province (name) VALUES ("Pontevedra");
INSERT INTO province (name) VALUES ("Rioja, La");
INSERT INTO province (name) VALUES ("Salamanca");
INSERT INTO province (name) VALUES ("Santa Cruz de Tenerife");
INSERT INTO province (name) VALUES ("Segovia");
INSERT INTO province (name) VALUES ("Sevilla");
INSERT INTO province (name) VALUES ("Soria");
INSERT INTO province (name) VALUES ("Tarragona");
INSERT INTO province (name) VALUES ("Teruel");
INSERT INTO province (name) VALUES ("Toledo");
INSERT INTO province (name) VALUES ("Valencia/València");
INSERT INTO province (name) VALUES ("Valladolid");
INSERT INTO province (name) VALUES ("Zamora");
INSERT INTO province (name) VALUES ("Zaragoza");